<?xml version="1.0" encoding="utf-8"?><Database Name="ICBF" Class="ORMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-TV3UORBS;Initial Catalog=ICBF;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="ICBFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ciudad" Member="Ciudad">
    <Type Name="Ciudad">
      <Column Name="idCiudad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Ciudad_Persona" Member="Persona" ThisKey="idCiudad" OtherKey="ciudadNacimiento" Type="Persona" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_DatosInfante" Member="DatosInfante" ThisKey="idUsuario" OtherKey="idAcudiente" Type="DatosInfante" />
      <Association Name="Persona_Usuario" Member="Persona" ThisKey="idPersona" OtherKey="idPersona" Type="Persona" IsForeignKey="true" />
      <Association Name="Rol_Usuario" Member="Rol" ThisKey="idRol" OtherKey="idRol" Type="Rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatosInfante" Member="DatosInfante">
    <Type Name="DatosInfante">
      <Column Name="idDatosInfante" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="eps" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idJardin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idAcudiente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idInfante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="peso" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="talla" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="fechaIngreso" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fechaSalida" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="DatosInfante_RegistroAcademico" Member="RegistroAcademico" ThisKey="idDatosInfante" OtherKey="idInfante" Type="RegistroAcademico" />
      <Association Name="DatosInfante_RegistroAsistencia" Member="RegistroAsistencia" ThisKey="idDatosInfante" OtherKey="idInfante" Type="RegistroAsistencia" />
      <Association Name="Usuario_DatosInfante" Member="Usuario" ThisKey="idAcudiente" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
      <Association Name="Jardin_DatosInfante" Member="Jardin" ThisKey="idJardin" OtherKey="idJardin" Type="Jardin" IsForeignKey="true" />
      <Association Name="Persona_DatosInfante" Member="Persona" ThisKey="idInfante" OtherKey="idPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Jardin" Member="Jardin">
    <Type Name="Jardin">
      <Column Name="idJardin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="idEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Jardin_DatosInfante" Member="DatosInfante" ThisKey="idJardin" OtherKey="idJardin" Type="DatosInfante" />
      <Association Name="Master_Jardin" Member="Master" ThisKey="idEstado" OtherKey="idMaster" Type="Master" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Master" Member="Master">
    <Type Name="Master">
      <Column Name="idMaster" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDependencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Master_Jardin" Member="Jardin" ThisKey="idMaster" OtherKey="idEstado" Type="Jardin" />
      <Association Name="Master_Master" Member="Master2" ThisKey="idMaster" OtherKey="idDependencia" Type="Master" />
      <Association Name="Master_Persona" Member="Persona" ThisKey="idMaster" OtherKey="tipoDocumento" Type="Persona" />
      <Association Name="Master_RegistroAcademico" Member="RegistroAcademico" ThisKey="idMaster" OtherKey="idNivel" Type="RegistroAcademico" />
      <Association Name="Master_RegistroAcademico1" Member="RegistroAcademico1" ThisKey="idMaster" OtherKey="idNota" Type="RegistroAcademico" />
      <Association Name="Master_RegistroAsistencia" Member="RegistroAsistencia" ThisKey="idMaster" OtherKey="estadoInfante" Type="RegistroAsistencia" />
      <Association Name="Master_Master" Member="Master1" ThisKey="idDependencia" OtherKey="idMaster" Type="Master" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permiso" Member="Permiso">
    <Type Name="Permiso">
      <Column Name="idPermiso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDependencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Permiso_Permiso" Member="Permiso2" ThisKey="idPermiso" OtherKey="idDependencia" Type="Permiso" />
      <Association Name="Permiso_PermisoRol" Member="PermisoRol" ThisKey="idPermiso" OtherKey="idPermiso" Type="PermisoRol" />
      <Association Name="Permiso_Permiso" Member="Permiso1" ThisKey="idDependencia" OtherKey="idPermiso" Type="Permiso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PermisoRol" Member="PermisoRol">
    <Type Name="PermisoRol">
      <Column Name="idPermisoRol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPermiso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Permiso_PermisoRol" Member="Permiso" ThisKey="idPermiso" OtherKey="idPermiso" Type="Permiso" IsForeignKey="true" />
      <Association Name="Rol_PermisoRol" Member="Rol" ThisKey="idRol" OtherKey="idRol" Type="Rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Persona" Member="Persona">
    <Type Name="Persona">
      <Column Name="idPersona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fechaNacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ciudadNacimiento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tipoSangre" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tipoDocumento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numeroDocumento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Persona_Usuario" Member="Usuario" ThisKey="idPersona" OtherKey="idPersona" Type="Usuario" />
      <Association Name="Persona_DatosInfante" Member="DatosInfante" ThisKey="idPersona" OtherKey="idInfante" Type="DatosInfante" />
      <Association Name="Ciudad_Persona" Member="Ciudad" ThisKey="ciudadNacimiento" OtherKey="idCiudad" Type="Ciudad" IsForeignKey="true" />
      <Association Name="Master_Persona" Member="Master" ThisKey="tipoDocumento" OtherKey="idMaster" Type="Master" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegistroAcademico" Member="RegistroAcademico">
    <Type Name="RegistroAcademico">
      <Column Name="idRegistroAcademiso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idInfante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="anioEscolar" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idNota" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fechaEntrega" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="DatosInfante_RegistroAcademico" Member="DatosInfante" ThisKey="idInfante" OtherKey="idDatosInfante" Type="DatosInfante" IsForeignKey="true" />
      <Association Name="Master_RegistroAcademico" Member="Master" ThisKey="idNivel" OtherKey="idMaster" Type="Master" IsForeignKey="true" />
      <Association Name="Master_RegistroAcademico1" Member="Master1" ThisKey="idNota" OtherKey="idMaster" Type="Master" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegistroAsistencia" Member="RegistroAsistencia">
    <Type Name="RegistroAsistencia">
      <Column Name="idRegistroAsistencia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idInfante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estadoInfante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="asistencia" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="DatosInfante_RegistroAsistencia" Member="DatosInfante" ThisKey="idInfante" OtherKey="idDatosInfante" Type="DatosInfante" IsForeignKey="true" />
      <Association Name="Master_RegistroAsistencia" Member="Master" ThisKey="estadoInfante" OtherKey="idMaster" Type="Master" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rol" Member="Rol">
    <Type Name="Rol">
      <Column Name="idRol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="habilitado" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Rol_Usuario" Member="Usuario" ThisKey="idRol" OtherKey="idRol" Type="Usuario" />
      <Association Name="Rol_PermisoRol" Member="PermisoRol" ThisKey="idRol" OtherKey="idRol" Type="PermisoRol" />
    </Type>
  </Table>
  <Table Name="dbo.ListarJardines" Member="ListarJardines">
    <Type Name="ListarJardines">
      <Column Name="idJardin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="jardin" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>